### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [sparshgup/QNL-Net#7]
I recently came across your project QNL-Net and I noticed that the repository github.com/sparshgup/QNL-Net currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by sparshgup** [comment]
Thanks for raising this issue! I added an MIT license, which would fit the purposes of the code being open-source. May I know if there's any specific purpose for which you needed a license for the code?

**Comment by cbjuan** [comment]
Thanks!
